// wrappers/react/SmartSearch.tsx
import React, { useRef, useEffect, useState, forwardRef, useImperativeHandle } from 'react';
import { defineCustomElements } from '@aravindaart/smart-search/loader';

export interface SearchResult {
  id: string | number;
  title: string;
  subtitle?: string;
  description?: string;
  category?: string;
  metadata?: Record<string, unknown>;
  icon?: string;
  url?: string;
  disabled?: boolean;
}

export interface SearchInputEventDetail {
  value: string;
  query: string;
}

export interface SearchSelectEventDetail {
  result: SearchResult;
  index: number;
}

export interface SmartSearchProps {
  placeholder?: string;
  value?: string;
  disabled?: boolean;
  loading?: boolean;
  clearable?: boolean;
  debounceTime?: number;
  minSearchLength?: number;
  maxResults?: number;
  theme?: 'light' | 'dark';
  autoFocus?: boolean;
  dataSource?: SearchResult[] | string;
  searchFields?: string[];
  filterMode?: 'contains' | 'startsWith' | 'fuzzy';
  caseSensitive?: boolean;
  groupBy?: string;
  noResultsMessage?: string;
  onSearchInput?: (event: SearchInputEventDetail) => void;
  onSearchClear?: () => void;
  onSearchFocus?: (event: FocusEvent) => void;
  onSearchBlur?: (event: FocusEvent) => void;
  onResultSelect?: (event: SearchSelectEventDetail) => void;
  onResultHover?: (event: SearchSelectEventDetail) => void;
  className?: string;
  style?: React.CSSProperties;
}

export interface SmartSearchRef {
  focus: () => void;
  blur: () => void;
  clear: () => void;
  setValue: (value: string) => void;
  getValue: () => string;
}

export const SmartSearch = forwardRef<SmartSearchRef, SmartSearchProps>(({
  placeholder = 'Search...',
  value = '',
  disabled = false,
  loading = false,
  clearable = true,
  debounceTime = 300,
  minSearchLength = 2,
  maxResults = 10,
  theme = 'light',
  autoFocus = false,
  dataSource = [],
  searchFields = ['title', 'subtitle', 'description'],
  filterMode = 'contains',
  caseSensitive = false,
  groupBy = '',
  noResultsMessage = 'No results found',
  onSearchInput,
  onSearchClear,
  onSearchFocus,
  onSearchBlur,
  onResultSelect,
  onResultHover,
  className,
  style,
  ...props
}, ref) => {
  const elementRef = useRef<any>(null);
  const [isReady, setIsReady] = useState(false);

  // Expose imperative methods
  useImperativeHandle(ref, () => ({
    focus: () => {
      if (elementRef.current) {
        const input = elementRef.current.shadowRoot?.querySelector('smart-search-input')?.shadowRoot?.querySelector('input');
        input?.focus();
      }
    },
    blur: () => {
      if (elementRef.current) {
        const input = elementRef.current.shadowRoot?.querySelector('smart-search-input')?.shadowRoot?.querySelector('input');
        input?.blur();
      }
    },
    clear: () => {
      if (elementRef.current) {
        elementRef.current.value = '';
      }
    },
    setValue: (newValue: string) => {
      if (elementRef.current) {
        elementRef.current.value = newValue;
      }
    },
    getValue: () => {
      return elementRef.current?.value || '';
    }
  }), []);

  // Initialize custom elements
  useEffect(() => {
    const initializeComponent = async () => {
      try {
        await defineCustomElements();
        await customElements.whenDefined('smart-search');
        setIsReady(true);
      } catch (error) {
        console.error('Failed to initialize SmartSearch component:', error);
      }
    };

    initializeComponent();
  }, []);

  // Set data source when component is ready
  useEffect(() => {
    if (isReady && elementRef.current && dataSource) {
      elementRef.current.dataSource = dataSource;
    }
  }, [isReady, dataSource]);

  // Set search fields when component is ready
  useEffect(() => {
    if (isReady && elementRef.current && searchFields) {
      elementRef.current.searchFields = searchFields;
    }
  }, [isReady, searchFields]);

  // Add event listeners when component is ready
  useEffect(() => {
    if (!isReady || !elementRef.current) return;

    const element = elementRef.current;

    const handleSearchInput = (event: CustomEvent<SearchInputEventDetail>) => {
      onSearchInput?.(event.detail);
    };

    const handleSearchClear = () => {
      onSearchClear?.();
    };

    const handleSearchFocus = (event: CustomEvent<FocusEvent>) => {
      onSearchFocus?.(event.detail);
    };

    const handleSearchBlur = (event: CustomEvent<FocusEvent>) => {
      onSearchBlur?.(event.detail);
    };

    const handleResultSelect = (event: CustomEvent<SearchSelectEventDetail>) => {
      onResultSelect?.(event.detail);
    };

    const handleResultHover = (event: CustomEvent<SearchSelectEventDetail>) => {
      onResultHover?.(event.detail);
    };

    // Add event listeners
    element.addEventListener('searchInput', handleSearchInput);
    element.addEventListener('searchClear', handleSearchClear);
    element.addEventListener('searchFocus', handleSearchFocus);
    element.addEventListener('searchBlur', handleSearchBlur);
    element.addEventListener('resultSelect', handleResultSelect);
    element.addEventListener('resultHover', handleResultHover);

    // Cleanup
    return () => {
      element.removeEventListener('searchInput', handleSearchInput);
      element.removeEventListener('searchClear', handleSearchClear);
      element.removeEventListener('searchFocus', handleSearchFocus);
      element.removeEventListener('searchBlur', handleSearchBlur);
      element.removeEventListener('resultSelect', handleResultSelect);
      element.removeEventListener('resultHover', handleResultHover);
    };
  }, [isReady, onSearchInput, onSearchClear, onSearchFocus, onSearchBlur, onResultSelect, onResultHover]);

  if (!isReady) {
    return <div className={className} style={style}>Loading...</div>;
  }

  return (
    <smart-search
      ref={elementRef}
      placeholder={placeholder}
      value={value}
      disabled={disabled}
      loading={loading}
      clearable={clearable}
      debounce-time={debounceTime}
      min-search-length={minSearchLength}
      max-results={maxResults}
      theme={theme}
      auto-focus={autoFocus}
      filter-mode={filterMode}
      case-sensitive={caseSensitive}
      group-by={groupBy}
      no-results-message={noResultsMessage}
      className={className}
      style={style}
      {...props}
    />
  );
});

SmartSearch.displayName = 'SmartSearch';

export default SmartSearch;

// src/components/smart-search/smart-search.tsx
import { Component, Prop, Event, EventEmitter, State, Element, Watch, h, Host } from '@stencil/core';
import { SearchResult, FilterMode, Theme, SearchInputEventDetail, SearchSelectEventDetail } from '../../types';
import { filterResults, generateId } from '../../utils/search';

@Component({
  tag: 'smart-search',
  styleUrl: 'smart-search.css',
  shadow: true,
})
export class SmartSearch {
  @Element() el!: HTMLElement;

  // Props - Inherit from both input and results components
  @Prop() placeholder: string = 'Search...';
  @Prop({ mutable: true }) value: string = '';
  @Prop() disabled: boolean = false;
  @Prop() loading: boolean = false;
  @Prop() clearable: boolean = true;
  @Prop() debounceTime: number = 300;
  @Prop() minSearchLength: number = 2;
  @Prop() maxResults: number = 10;
  @Prop() theme: Theme = 'light';
  @Prop() autoFocus: boolean = false;

  // Search specific props
  @Prop() dataSource: SearchResult[] | string = [];
  @Prop() searchFields: string[] = ['title', 'subtitle', 'description'];
  @Prop() filterMode: FilterMode = 'contains';
  @Prop() caseSensitive: boolean = false;
  @Prop() groupBy: string = '';
  @Prop() noResultsMessage: string = 'No results found';

  // Events
  @Event() searchInput!: EventEmitter<SearchInputEventDetail>;
  @Event() searchClear!: EventEmitter<void>;
  @Event() searchFocus!: EventEmitter<FocusEvent>;
  @Event() searchBlur!: EventEmitter<FocusEvent>;
  @Event() resultSelect!: EventEmitter<SearchSelectEventDetail>;
  @Event() resultHover!: EventEmitter<SearchSelectEventDetail>;

  // State
  @State() isOpen: boolean = false;
  @State() filteredResults: SearchResult[] = [];
  @State() isLoading: boolean = false;
  @State() searchId: string = generateId('smart-search');

  private searchInputRef!: HTMLSmartSearchInputElement;
  private searchResultsRef!: HTMLSmartSearchResultsElement;
  private staticDataSource: SearchResult[] = [];

  @Watch('dataSource')
  updateDataSource() {
    if (Array.isArray(this.dataSource)) {
      this.staticDataSource = this.dataSource;
    } else if (typeof this.dataSource === 'string') {
      // API endpoint - we'll implement this later
      this.staticDataSource = [];
    }
  }

  @Watch('theme')
  updateTheme() {
    this.el.setAttribute('data-theme', this.theme);
  }

  componentWillLoad() {
    this.updateDataSource();
  }

  componentDidLoad() {
    this.el.setAttribute('data-theme', this.theme);
    
    // Add click outside listener
    document.addEventListener('click', this.handleClickOutside);
    document.addEventListener('focusin', this.handleFocusChange);
  }

  disconnectedCallback() {
    document.removeEventListener('click', this.handleClickOutside);
    document.removeEventListener('focusin', this.handleFocusChange);
  }

  private handleClickOutside = (event: Event) => {
    if (!this.el.contains(event.target as Node)) {
      this.closeResults();
    }
  };

  private handleFocusChange = (event: FocusEvent) => {
    if (!this.el.contains(event.target as Node)) {
      this.closeResults();
    }
  };

  private async performSearch(query: string): Promise<SearchResult[]> {
    if (typeof this.dataSource === 'string') {
      // API search
      try {
        this.isLoading = true;
        const response = await fetch(`${this.dataSource}?q=${encodeURIComponent(query)}`);
        const data = await response.json();
        return Array.isArray(data) ? data : data.results || [];
      } catch (error) {
        // eslint-disable-next-line no-console
        console.error('Search API error:', error);
        return [];
      } finally {
        this.isLoading = false;
      }
    } else {
      // Static data search
      return filterResults(
        this.staticDataSource,
        query,
        this.filterMode,
        this.searchFields,
        this.caseSensitive
      );
    }
  }

  private handleSearchInput = async (event: CustomEvent<SearchInputEventDetail>) => {
    const { query } = event.detail;
    this.value = query;

    // Emit the search input event
    this.searchInput.emit(event.detail);

    if (query.length >= this.minSearchLength) {
      this.isOpen = true;
      this.filteredResults = await this.performSearch(query);
    } else if (query.length === 0) {
      this.isOpen = false;
      this.filteredResults = [];
    }
  };

  private handleSearchClear = () => {
    this.value = '';
    this.isOpen = false;
    this.filteredResults = [];
    this.searchClear.emit();
  };

  private handleSearchFocus = (event: CustomEvent<FocusEvent>) => {
    this.searchFocus.emit(event.detail);
    
    // Show results if we have a search value
    if (this.value.length >= this.minSearchLength) {
      this.isOpen = true;
    }
  };

  private handleSearchBlur = (event: CustomEvent<FocusEvent>) => {
    // Delay closing to allow for result selection
    setTimeout(() => {
      this.searchBlur.emit(event.detail);
    }, 150);
  };

  private handleResultSelect = (event: CustomEvent<SearchSelectEventDetail>) => {
    const { result } = event.detail;
    
    // Update input value with selected result
    this.value = result.title;
    this.closeResults();
    
    // Emit the selection event
    this.resultSelect.emit(event.detail);
    
    // Update input component value
    if (this.searchInputRef) {
      this.searchInputRef.value = result.title;
    }
  };

  private handleResultHover = (event: CustomEvent<SearchSelectEventDetail>) => {
    this.resultHover.emit(event.detail);
  };

  private closeResults() {
    this.isOpen = false;
  }

  private updateInputAriaAttributes() {
    if (this.searchInputRef && this.searchResultsRef) {
      const input = this.searchInputRef.shadowRoot?.querySelector('input');
      if (input) {
        input.setAttribute('aria-expanded', this.isOpen.toString());
        input.setAttribute('aria-owns', 'search-results-list');
      }
    }
  }

  componentDidUpdate() {
    this.updateInputAriaAttributes();
  }

  render() {
    const containerClasses = {
      'smart-search-container': true,
      'smart-search-container--open': this.isOpen,
      'smart-search-container--loading': this.isLoading || this.loading,
    };

    return (
      <Host>
        <div class={containerClasses}>
          <smart-search-input
            ref={el => this.searchInputRef = el}
            placeholder={this.placeholder}
            value={this.value}
            disabled={this.disabled}
            loading={this.isLoading || this.loading}
            clearable={this.clearable}
            debounceTime={this.debounceTime}
            minSearchLength={this.minSearchLength}
            theme={this.theme}
            autoFocus={this.autoFocus}
            onSearchInput={this.handleSearchInput}
            onSearchClear={this.handleSearchClear}
            onSearchFocus={this.handleSearchFocus}
            onSearchBlur={this.handleSearchBlur}
          />

          {h('smart-search-results', {
            ref: el => this.searchResultsRef = el,
            results: this.filteredResults,
            loading: this.isLoading,
            visible: this.isOpen,
            maxResults: this.maxResults,
            groupBy: this.groupBy,
            highlightTerm: this.value,
            noResultsMessage: this.noResultsMessage,
            theme: this.theme,
            onResultSelect: this.handleResultSelect,
            onResultHover: this.handleResultHover,
          })}
        </div>
      </Host>
    );
  }
}
